# Site settings
title: Scott
email: sfunkhouser@gmail.com
description: Personal site and blog of Scott Funkhouser
baseurl: ""

twitter_username: saf6
github_username:  funkhou9

url: http://www.scottafunkhouser.com

# Build settings
markdown: kramdown
